name: Release

on:
push:
tags:
- 'v..*'

jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4

name: Set up Python
uses: actions/setup-python@v5
with:
python-version: '3.11'

name: Run basic checks
run: |
python -m compileall custom_components
